### ISSUE TITLE
No color for vim-airline after startup

### ISSUE THREAD

**Issue by andrewbenton** [dan-f/vim-daylight#1]
When using vim-daylight with vim-airline and vim-plug to load two (also plug loaded) color schemes, the color for vim-airline is not set on startup.  All plugins are loaded by vim-plug.  The loaded color schemes are Revolution.vim and vim-gotham.

**Comment by dan-f** [comment]
Thanks for the heads up, @andrewbenton. Did @jesson's PR fix your issue?

**Comment by dan-f** [comment]
I'm assuming #2 solved this. Closing now.

**Comment by andrewbenton** [comment]
Sorry for the late reply.  @jesson's fix did fix issues with the display on some machines that I use, but I still have issues with the 'set background=light'.  The problem with airline was that the colorscheme seems to actually need a colorscheme for airline as well as vim in general.

**Comment by andrewbenton** [comment]
Ideally, I would like to be able to set a default background, and then have that enforced in the case that the colorscheme doesn't set it, but I don't know if that's possible.

**Comment by dan-f** [comment]
@andrewbenton I don't understand the issue with `set background=light` that you're describing. I'd be happy to entertain a PR, if you like, but I don't use or work on this plugin anymore.
